defaults: &defaults
  adapter: postgresql
  encoding: unicode
  host:     localhost
  port:     5432
  username: postgres
  password: postgres


development:
  <<: *defaults
  database: db/site_catei_dev

test:
  <<: *defaults
  database: db/site_catei_test

production:
  <<: *defaults
  database: db/site_catei_production
